# 清华大学镜像 https://mirror.tuna.tsinghua.edu.cn/help/CocoaPods/
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '11.0'

# 增加source，这样就能找到私有pod
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/RiverYangZiJiang/Specs.git'

#如果在Podfile中没有指定target，那么只有工程里的第一个target能够使用Podfile中描述的Pods依赖库。http://blog.csdn.net/wzzvictory/article/details/19178709
target 'AllInCode' do

inhibit_all_warnings!
#use_modular_headers!

# 组件化
pod 'CTMediator', :modular_headers => true
# 直接指定私有pod路径，这样会Pre-downloading PrivatePod
#pod 'PrivatePod', :git => 'https://github.com/RiverYangZiJiang/PrivatePod.git'
pod 'PrivatePod'
pod 'YZJA'
pod 'YZJB'
#pod 'YZJSwift'
#pod 'YZJA_Category'
#pod 'A'

# 网络请求
pod 'AFNetworking', "~> 3.2.1"
pod 'ASIHTTPRequest'
# 网络监控
pod 'Reachability'

#字典转模型
pod 'MJExtension'
# 下拉刷新
pod 'MJRefresh'
# 图片加载
pod 'SDWebImage',  '~> 5.0.0'

#用于适配
pod 'Masonry'

#友盟统计和分享
pod 'UMengAnalytics'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/Sina'

#百度地图SDK
pod 'BaiduMapKit', "~> 3.4.4"

pod 'CYLTabBarController'

# 表情键盘
pod 'HMEmoticon'
# 正则匹配点击
pod 'KILabel'

# 通用链接跳转
pod 'MagicWindowSDK'

# 数据库 新浪微博用
pod 'FMDB'

# 蒙版
pod 'MBProgressHUD'

# 进度
pod 'M13ProgressSuite'

# 无线轮播
pod 'SDCycleScrollView'

# 键盘管理
pod 'IQKeyboardManager'

# 唯一设备标识
pod 'FCUUID'


# 三级联动 时间 地址
#pod 'MOFSPickerManager', "~> 2.0.2"
pod 'MOFSPickerManager', "~> 3.0.0"


# 全局滑动
pod 'FDFullscreenPopGesture'

# toast
pod 'Toast'

# 二维码
pod 'HMQRCodeScanner'

# 照片
pod 'TZImagePickerController', "~>2.0.0.9"

# scrollpageView
pod 'ZJScrollPageView'

# 列表视频
pod 'ZFPlayer', "~> 2.1.6"
pod 'ZFDownload'

# mark- 好玩的
# 泡泡uibutton
pod 'DWBubbleMenuButton'

# 动态 collectionView
#pod 'LxGridView'
# 指纹识别
#pod 'TDTouchID'
# h5交互
#pod 'WebViewJavascriptBridge'
# YYKit
#pod 'YYKit'
# 脸部识别
#pod 'iflyMSC'
# 环信连天包含实时语音版本
# pod 'Hyphenate'
# pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

pod 'AvoidCrash'  # 防止崩溃
pod 'MLeaksFinder'  # MLeaksFinder helps you find memory leaks in your iOS apps at develop time. It can automatically find leaks in UIView and UIViewController objects, present an alert with the leaked object in its View-ViewController stack when leaks happening.
pod 'WoodPeckeriOS' # View simulator & real device sandbox files, UserDefaults, network request from Mac.

pod 'ZJAnimationPopView'  # A fast, convenient view to show animation pop view,it support 72 kinds of animation pop effect.
pod 'LYEmptyView', "~> 1.2.3"  # 一行代码集成空白页面占位图(无数据、无网络占位图)

pod 'JKCountDownButton'  # 倒计时按钮，封装得很好，倒计时结束之前不让点击

#pod 'YYKit'
pod 'YYCache' # 高性能内存和磁盘缓存
pod 'YYModel'
pod 'YYImage'
pod 'YYText'
pod 'YYAsyncLayer'
pod 'YYCategories'
end
